# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: desklab
description: desklab support page
baseurl: / # the subpath of your site, e.g. /support
url: https://support.desk-lab.de # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:categories/:title

content_type: #Define whether this is a knowledge base, help center, or something else
use_authors: false #Set this to false to disable showing post authors

brand_logo: desklab-logo.png
brand_name: desklab
header: How can we help you?
subheader: Support and documentation for desklab devices

meta_image: meta.png

# Social Links
twitter_username: desklab_ug
facebook_page: https://www.facebook.com/desklab-Faszination-Forschung-865449063665943/
github_username: desklab
email: orga@desk-lab.de
linkedin_page:
instagram_username: desklab_ug


# Navivation
nav_item_one: GitHub
nav_item_one_link: https://github.com/desklab/

nav_item_two: desklab Lehrerportal
nav_item_two_link: https://desk-lab.de/docs/#

nav_item_three: #
nav_item_three_link: #

nav_button: desklab Homepage
nav_button_link: https://desk-lab.de/

# More Help
help_one_title: Fehler gefunden?
help_one_content: Verbesserungsvorschläge oder Fehler können als Issue auf Github eingereicht bzw. gemeldet werden.
help_one_button: Github Issues
help_one_link: https://github.com/desklab/desklab.github.io

help_two_title: Unterrichtsmaterial
help_two_content: Dokumente für den Gebrauch im Unterricht sind im desklab-Lehrerportal hinterlegt.
help_two_button: desklab Lehrerportal
help_two_link: https://desk-lab.de/docs/

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-last-modified-at

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#


sass:
  sass_dir:          _scss
  style:            :compressed
